language: python
python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_SPEC=Django~=1.5
  - DJANGO_SPEC=Django~=1.6
  - DJANGO_SPEC=Django~=1.7
  - DJANGO_SPEC=Django~=1.8
  - DJANGO_SPEC=https://github.com/django/django/zipball/master\#egg\Django

install:
  - pip install coveralls --use-mirrors
  - pip install --use-mirrors $DJANGO_SPEC
  - python setup.py install

script:
  - coverage run --source=rebar setup.py test

after_success:
  - coveralls
