language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO_SPEC=Django==1.5.5
  - DJANGO_SPEC=Django==1.6.2
  - DJANGO_SPEC=https://github.com/django/django/zipball/master\#egg\Django

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_SPEC=https://github.com/django/django/zipball/master\#egg\Django

install:
  - pip install coveralls --use-mirrors
  - pip install --use-mirrors $DJANGO_SPEC
  - pip install Sphinx
  - python setup.py install

script:
  - coverage run --source=rebar setup.py test
  - sphinx-build -E -W -b doctest docs build

after_success:
  - coveralls